classdef CSP_template < audioPlugin
    % downloaded from: bennettaudio.com
    
    properties
        % a property is a public variable that usually has a parameter
        % associated with it

        % PARAMETER_NAME = some value;

        ATTACK = 10; %milliseconds
        RELEASE = 50;
        RATIO = 6;
        THRESHOLD = -30;
        COMP_MIX = 50.0;
         % EQ parameters
        LF_SHELF = 100;
        MF_FREQ = 1000;
        HF_SHELF = 8000;
        
        LF_GAIN = 0;
        MF_GAIN = 0;
        HF_GAIN = 0;
        %Pitch shift parameters
        % Amount of pitch shift (in semi-tones)
        % Valid ranges are from -12 to 12
        PITCHSHIFT = 0;
        
        % Delay line overlap
        OVERLAP = 0.01;
        %Pitch Mix
        PITCHSHIFT_MIX = 50.0;
    end

    properties (Constant)
        % this contains instructions to build your plugin GUI, usually
        % populated with audioPluginParamters that link to properties
        
        % parameters have:
        % a function call - audioPluginParameter('PARAMETER_NAME',...
        %'DisplayName'
        %'Label'
        %'Mapping': 'lin', 'log', 'pow', 'int', 'enum'

        PluginInterface = audioPluginInterface(...
            'PluginName','SimpleGain',...
            'VendorName', 'DigitalAudioTheory1',...
            'VendorVersion', '1.0.0',...
            'UniqueId','DATg',...
                audioPluginGridLayout(...
                'RowHeight', [25 85 25 85 25 85 25 85 25 85 85],...
                'ColumnWidth',[85 85 85 85]),...
                audioPluginParameter("PITCHSHIFT",...
                DisplayName="Pitch", ...
                Label="semitones", ...
                DisplayNameLocation="above", ...
                Mapping={"int",-12,12}, ...
                Style="rotaryknob", Layout=[8 3], ...
                Filmstrip = 'dial.png', ...
                FilmstripFrameSize = [65 65]), ...
                audioPluginParameter("OVERLAP", ...
                DisplayName="Smoothness", ...
                DisplayNameLocation="above", ...
                Mapping={"lin",.01,.5}, ...
                Style="rotaryknob", Layout=[8 4], ...
                Filmstrip = 'dial.png', ...
                FilmstripFrameSize = [65 65]), ... %end of param
                audioPluginParameter('ATTACK', ...
                'DisplayName', 'Attack', ...
                'Style', 'rotaryknob',...
                'Mapping', {'lin', 0, 50},...
                'Layout', [6,1;6,2],...
                'DisplayNameLocation','above',...
                'Label', 'ms', ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ),...%end of param
                audioPluginParameter('RELEASE', ...
                'DisplayName', 'Release', ...
                'Style', 'rotaryknob',...
                'Layout', [8,1; 8,2],...
                'DisplayNameLocation','above',...
                'Label', 'ms', ...
                'Mapping', {'lin', 0, 200}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ),...%end of param
                audioPluginParameter('THRESHOLD', ...
                'DisplayName', 'Threshold', ...
                'Style', 'rotaryknob',...
                'Layout', [2, 1; 2,2],...
                'DisplayNameLocation','above',...
                'Label', 'dB', ...
                'Mapping', {'lin', -50, 0}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ),...%end of param
                audioPluginParameter('RATIO', ...
                'DisplayName', 'Ratio', ...
                'Style', 'rotaryknob',...
                'Layout', [4, 1; 4,2],...
                'DisplayNameLocation','above',...
                'Label', ':1', ...
                'Mapping', {'int', 1, 12}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                )...%end of param
                 ,audioPluginParameter('LF_SHELF',...
                'DisplayName', 'Lows',...
                'Style', 'rotaryknob',...
                'Layout', [2, 3],...
                'DisplayNameLocation','above',...
                'Label', 'Hz',...
                'Mapping', {'log', 20, 400}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65]), ... % end of parameter
            audioPluginParameter('LF_GAIN',...
                'DisplayName', '-/+',...
                'Style', 'rotaryknob',...
                'Layout', [2, 4],...
                'DisplayNameLocation','above',...
                'Label', 'dB',...
                'Mapping', {'lin', -15, 15}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ), ... % end of parameter
            audioPluginParameter('MF_FREQ',...
                'DisplayName', 'Mids',...
                'Style', 'rotaryknob',...
                'Layout', [4, 3],...
                'DisplayNameLocation','above',...
                'Label', 'Hz', ...
                'Mapping', {'log', 200, 8000}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ), ... % end of parameter
            audioPluginParameter('MF_GAIN',...
                'DisplayName', '-/+',...
                'Style', 'rotaryknob',...
                'Layout', [4, 4],...
                'DisplayNameLocation','above',...
                'Label', 'dB',...
                'Mapping', {'lin', -15, 15}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ), ... % end of parameter
            audioPluginParameter('HF_SHELF',...
                'DisplayName', 'Highs',...
                'Style', 'rotaryknob',...
                'Layout', [6, 3],...
                'DisplayNameLocation','above',...
                'Label', 'Hz',...
                'Mapping', {'log', 2000, 16000}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ), ... % end of parameter
            audioPluginParameter('HF_GAIN',...
                'DisplayName', '-/+',...
                'Style', 'rotaryknob',...
                'Layout', [6, 4],...
                'DisplayNameLocation','above',...
                'Label', 'dB',...
                'Mapping', {'lin', -15, 15}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65] ...
                ), ...
                audioPluginParameter('COMP_MIX',...
                'DisplayName', 'Compgression',...
                'Style', 'rotaryknob',...
                'Layout', [10,1;11,2],...
                'DisplayNameLocation', 'above',...
                'Label', '%',...
                'Mapping', {'lin', 1.0, 100.0}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65]),...
                audioPluginParameter('PITCHSHIFT_MIX',...
                'DisplayName', 'Shiftyness',...
                'Style', 'rotaryknob',...
                'Layout', [10,3;11,4],...
                'DisplayNameLocation', 'above',...
                'Label', '%',...
                'Mapping', {'lin', 1.0, 100.0}, ...
                'Filmstrip', 'dial.png',...
                'FilmstripFrameSize', [65 65]),...
                'BackgroundImage','Background.png')
        % end of interface
        
    end

    properties (Access = private)
        %internal filter variables, such as coefficient values
        FS = 44100;
        compressor;
        EQ;
        PitchShifter;
    end
    
    methods
        function plugin = CSP_template()
             % Do any initializing that needs to occur BEFORE the plugin runs

             % Initialize Compressor
            plugin.compressor = compressor('MakeUpGainMode','Auto');
            updateCompressor(plugin);
            % Initialize EQ
plugin.EQ = multibandParametricEQ('SampleRate', plugin.FS, ...
                'NumEQBands', 3, ...
                'SampleRate', plugin.FS,...
                'Frequencies', [plugin.LF_SHELF, plugin.MF_FREQ, plugin.HF_SHELF], ...
                'PeakGains', [plugin.LF_GAIN, plugin.MF_GAIN, plugin.HF_GAIN]...
                );
           % Initialize Pitch Shifter
           plugin.PitchShifter = audiopluginexample.PitchShifter();

        end

        function out = process(plugin,in)
            % DSP section
            %gain = db2mag(plugin.GAIN_DB);
            %out = gain * in;
            pitchShift = (plugin.PitchShifter(in*(plugin.PITCHSHIFT_MIX/100.0)));
            comp = (plugin.compressor(in * (plugin.COMP_MIX/100.0)+pitchShift));
            eq = plugin.EQ(comp);
            out =  eq ;
            
        end
        
        function reset(plugin)
            % this gets called if the sample rate changes or if the plugin
            % gets reloaded
            
            plugin.FS = getSampleRate(plugin);

            
        end
        
        function set.PITCHSHIFT(plugin, val)
            plugin.PITCHSHIFT = val;
            updatePitchShifter(plugin);
        end

        function set.OVERLAP(plugin, val)
            plugin.OVERLAP = val;
            updatePitchShifter(plugin);
        end

        function updatePitchShifter(plugin)
            plugin.PitchShifter.PitchShift = plugin.PITCHSHIFT;
            plugin.PitchShifter.Overlap = plugin.OVERLAP;
        end

        function set.LF_SHELF(plugin, val)
            plugin.LF_SHELF = val;
            updateEQ(plugin);
        end

        function set.LF_GAIN(plugin, val)
            plugin.LF_GAIN = val;
            updateEQ(plugin);
        end

        function set.MF_FREQ(plugin, val)
            plugin.MF_FREQ = val;
            updateEQ(plugin);
        end

        function set.MF_GAIN(plugin, val)
            plugin.MF_GAIN = val;
            updateEQ(plugin);
        end


        function set.HF_SHELF(plugin, val)
            plugin.HF_SHELF = val;
            updateEQ(plugin);
        end

        function set.HF_GAIN(plugin, val)
            plugin.HF_GAIN = val;
            updateEQ(plugin);
        end


        function updateEQ(plugin)
            plugin.EQ.Frequencies = [plugin.LF_SHELF, plugin.MF_FREQ, plugin.HF_SHELF];
            plugin.EQ.PeakGains = [plugin.LF_GAIN, plugin.MF_GAIN, plugin.HF_GAIN];
        end
        
       function set.THRESHOLD(plugin, val)
            plugin.THRESHOLD = val;
            updateCompressor(plugin);
        end

        function set.RATIO(plugin, val)
            plugin.RATIO = val;
            updateCompressor(plugin);
        end

        function set.ATTACK(plugin, val)
            plugin.ATTACK = val;
            updateCompressor(plugin);
        end

        function set.RELEASE(plugin, val)
            plugin.RELEASE = val;
            updateCompressor(plugin);
        end
        
        function set.COMP_MIX(plugin, val)
            plugin.COMP_MIX = val;
        end
        function set.PITCHSHIFT_MIX(plugin, val)
            plugin.PITCHSHIFT_MIX = val;
        end
        function updateCompressor(plugin)
            plugin.compressor.Threshold = plugin.THRESHOLD;
            plugin.compressor.Ratio = plugin.RATIO;
            plugin.compressor.AttackTime = plugin.ATTACK/1000;
            plugin.compressor.ReleaseTime = plugin.RELEASE/1000;
        end
        
    end
end